In [127]:
import requests
from bs4 import BeautifulSoup
from time import sleep
from urllib.parse import unquote

import pandas as pd
import numpy as np
import re

In [2]:
HEADERS = {"User-Agent": "qangos-scraper/1.0(contact:q@bradtaba.org)"}
API = "https://onepiece.fandom.com/api.php"

character_columns = [
    'Official English Name',
    'Debut',
    'Affiliations',
    'Occupations',
    'Origin',
    'Status',
    'Age',
    'Birthday',
    'Height',
    'Blood Type',
    'Bounty'
]

In [3]:
def fetch_onepiece(page, sleep_time=1):
    params = {
        "action": "parse",
        "page": unquote(page),
        "prop": "text",
        "format": "json"
    }

    try:
        r = requests.get(API, params=params, headers=HEADERS, timeout=30)
        data = r.json()
        html = data["parse"]["text"]["*"]
        sleep(sleep_time)
    except:
        return False
    else:
        print(f"Page has been successfully fetched! {page}")

    return html

In [4]:
character_page = fetch_onepiece("List_of_Canon_Characters")
soup = BeautifulSoup(character_page, 'html5lib')

char_table = []
for i in soup.tr.find_next_siblings():
    char_data = {
        'name': i.a.text,
        'link': i.a['href'][2:].split('/')[-1]
    }
    char_table.append(char_data)
    
char_table = pd.DataFrame(char_table)

Page has been successfully fetched! List_of_Canon_Characters

In [5]:
status_pattern = r'\(.*?$'
status_regex = re.compile(status_pattern)

name_pattern = r' \(.*?\)'
name_regex = re.compile(name_pattern)

bday_pattern = r'\b[a-z]+\b \d{1,2}'
bday_regex = re.compile(bday_pattern, re.I)

age_pattern = r'\d+'
age_regex = re.compile(age_pattern)

height_pattern = r'\b\d+\s*cm\b'
height_regex = re.compile(height_pattern)

height_m_pattern = r'\b(\d+)\s*m\b'
height_m_regex = re.compile(height_m_pattern)

height_km_pattern = r'\b(\d+)\s*km\b'
height_km_regex = re.compile(height_km_pattern)

hyperlink_pattern = r'\[\d+\]'
hyperlink_regex = re.compile(hyperlink_pattern)

debut_pattern = r'Chapter (\d+)'
debut_regex = re.compile(debut_pattern, re.I)

bounty_edgecase_pattern = r'\(At least (.*?)\)'
bounty_edgecase_regex = re.compile(bounty_edgecase_pattern, re.I)

bounty_edgecase2_pattern = r'\(([0-9,]*)\)'
bounty_edgecase2_regex = re.compile(bounty_edgecase2_pattern, re.I)

In [6]:
armament_page = fetch_onepiece('Haki/Armament_Haki')
armament_soup = BeautifulSoup(armament_page, 'html5lib')

armament_users = []

for i in armament_soup.find_all('small'):
    armament_users.append(status_regex.sub('',i.text).strip())

Page has been successfully fetched! Haki/Armament_Haki

In [7]:
conq_page = fetch_onepiece('Haki/Supreme_King_Haki')
conq_soup = BeautifulSoup(conq_page, 'html5lib')

conq_users = []

for i in conq_soup.find_all('small'):
    conq_users.append(status_regex.sub('',i.text).strip())

Page has been successfully fetched! Haki/Supreme_King_Haki

In [8]:
observation_page = fetch_onepiece('Haki/Observation_Haki')
observation_soup = BeautifulSoup(observation_page, 'html5lib')

observation_users = []

for i in observation_soup.find_all('small'):
    observation_users.append(status_regex.sub('',i.text).strip())

Page has been successfully fetched! Haki/Observation_Haki

In [9]:
def clean_data(luffy_dict):
    if 'Official English Name' in luffy_dict: 
        luffy_dict['Official English Name'] = name_regex.sub('', luffy_dict['Official English Name'].split(';')[0])

    if 'Occupations' in luffy_dict:
        luffy_dict['Occupations'] = luffy_dict['Occupations'].split(';')[0]

    if 'Bounty' in luffy_dict:
        if luffy_dict['Bounty'].lower().startswith('(') and luffy_dict['Bounty'].lower().endswith(')'):
            luffy_dict['Bounty'] = luffy_dict['Bounty'][1:-1]

        if isinstance(luffy_dict['Bounty'], int):
            luffy_dict['Bounty'] = luffy_dict['Bounty']
        elif bounty_edgecase_regex.findall(luffy_dict['Bounty']):
            luffy_dict['Bounty'] = int(''.join(bounty_edgecase_regex.findall(luffy_dict['Bounty'])[-1].split(',')))
        elif (luffy_dict['Bounty'].lower().startswith('at')):
            if bounty_edgecase2_regex.findall(luffy_dict['Bounty']):
                luffy_dict['Bounty'] = int(''.join(bounty_edgecase2_regex.findall(luffy_dict['Bounty'])[-1].split(',')))
            else:
                luffy_dict['Bounty'] = int(''.join((luffy_dict['Bounty'].split(' ')[-1]).split(',')))
        elif (luffy_dict['Bounty'].lower().startswith('unknown')):
            luffy_dict['Bounty'] = 0
        elif luffy_dict['Bounty'].lower().startswith('¥'):
            luffy_dict['Bounty'] = int(''.join((luffy_dict['Bounty'][1:].split(' ')[0]).split(',')))
        elif luffy_dict['Bounty'].lower().startswith('over'):
            luffy_dict['Bounty'] = int(''.join((luffy_dict['Bounty'].split(' ')[1]).split(',')))
        elif luffy_dict['Bounty'].lower().startswith('less'):
            luffy_dict['Bounty'] = int(''.join((luffy_dict['Bounty'].split(' ')[2]).split(',')))
        elif bounty_edgecase2_regex.findall(luffy_dict['Bounty']):
            luffy_dict['Bounty'] = int(''.join(bounty_edgecase2_regex.findall(luffy_dict['Bounty'])[-1].split(',')))
        else:
            luffy_dict['Bounty'] = int(''.join((luffy_dict['Bounty'].split(' ')[0]).split(',')))

    if 'Origin' in luffy_dict:
        luffy_dict['Origin'] = ' '.join(luffy_dict['Origin'].split()[:2])

    if 'Birthday' in luffy_dict:
        luffy_dict['Birthday'] = bday_regex.findall(luffy_dict['Birthday'])[0]

    if 'Age' in luffy_dict:
        ages = age_regex.findall(luffy_dict['Age'].split(';')[-1].strip())
        if ages:
            luffy_dict['Age'] = int(ages[0])
        elif luffy_dict['Age'] == 'Multiple Centuries':
            luffy_dict['Age'] = 100
        else:
            luffy_dict['Age'] = 0

    if 'Height' in luffy_dict:
        cm = height_regex.findall(luffy_dict['Height'])
        m = height_m_regex.findall(luffy_dict['Height'])
        km = height_km_regex.findall(luffy_dict['Height'])
        if cm:
            luffy_dict['Height'] = int(cm[-1][:-3])
        elif m:
            luffy_dict['Height'] = int(m[-1])*100
        elif km:
            luffy_dict['Height'] = int(km[-1])*1000
        else:
            luffy_dict['Height'] = np.nan

    if 'Debut' in luffy_dict:
        chap = debut_regex.findall(luffy_dict['Debut'])
        if chap:
            luffy_dict['Debut'] = int(chap[0])
        else:
            luffy_dict['Debut'] = np.nan

    return luffy_dict

In [10]:
character_info_list = []

In [13]:
for link in char_table['link'].to_list():
    luffy_page = fetch_onepiece(link)
    if not luffy_page:
        print(f'skip: {link}. index {int(char_table[char_table['link']==link].index[0])}')
        print('Next:', int(char_table[char_table['link']==link].index[0])+1)
        continue
    luffy_soup = BeautifulSoup(luffy_page, 'html5lib')

    luffy_dict = {}
    for i in luffy_soup.find_all(class_='pi-data-label pi-secondary-font'):
        if i.text[:-1] in character_columns:
            if i.text[:-1]=='Affiliations':
                luffy_dict[i.text[:-1]] = [a['title'] for a in i.find_next_sibling().find_all('a', title=True)]
            else:
                luffy_dict[i.text[:-1]] = hyperlink_regex.sub(' ', i.find_next_sibling().text).strip()

    fruit_data = luffy_soup.find_all('span', class_='pi-data-label pi-secondary-font')
    if fruit_data:
        luffy_dict['Devil Fruit'] = 1
        luffy_dict['Fruit Type'] = hyperlink_regex.sub(' ', fruit_data[-1].find_next_sibling().text).strip()
    else:
        luffy_dict['Devil Fruit'] = 0

    if 'Official English Name' in luffy_dict:
        luffy_dict['Observation Haki'] = 1 if luffy_dict['Official English Name'] in observation_users else 0
        luffy_dict['Armament Haki'] = 1 if luffy_dict['Official English Name'] in armament_users else 0
        luffy_dict['Conquerers Haki'] = 1 if luffy_dict['Official English Name'] in conq_users else 0
    else:
        luffy_dict['Observation Haki'] = 0
        luffy_dict['Armament Haki'] = 0
        luffy_dict['Conquerers Haki'] = 0

    character_info_list.append(clean_data(luffy_dict))
    print('Next:', int(char_table[char_table['link'] == link].index[0])+1)

Page has been successfully fetched! A_O
Next: 1
Page has been successfully fetched! Abdullah
Next: 2
Page has been successfully fetched! Absalom
Next: 3
Page has been successfully fetched! Acilia
Next: 4
Page has been successfully fetched! Adele
Next: 5
Page has been successfully fetched! Aegir
Next: 6
Page has been successfully fetched! Ageha_Woman
Next: 7
Page has been successfully fetched! Aggie_68
Next: 8
Page has been successfully fetched! Agotogi
Next: 9
Page has been successfully fetched! Agsilly
Next: 10
Page has been successfully fetched! Agyo
Next: 11
Page has been successfully fetched! Ahho_Desunen_IX
Next: 12
Page has been successfully fetched! Ahho_Zurako
Next: 13
Page has been successfully fetched! Ahiru
Next: 14
Page has been successfully fetched! Aisa
Next: 15
Page has been successfully fetched! Akehende
Next: 16
Page has been successfully fetched! Akudai_Kanzaburo
Next: 17
Page has been successfully fetched! Akumai
Next: 18
Page has been successfully fetched! Aladine
Next: 19
Page has been successfully fetched! Albion
Next: 20
Page has been successfully fetched! Alice
Next: 21
Page has been successfully fetched! Ally
Next: 22
Page has been successfully fetched! Alpacaman
Next: 23
Page has been successfully fetched! Alpha
Next: 24
Page has been successfully fetched! Alvida
Next: 25
Page has been successfully fetched! Amadob
Next: 26
Page has been successfully fetched! Amazon
Next: 27
Page has been successfully fetched! An_Zengaiina
Next: 28
Page has been successfully fetched! Anba
Next: 29
Page has been successfully fetched! Baskerville
Next: 30
Page has been successfully fetched! Andre
Next: 31
Page has been successfully fetched! Ange
Next: 32
Page has been successfully fetched! Anjo
Next: 33
Page has been successfully fetched! Ankoro
Next: 34
Page has been successfully fetched! Antonio
Next: 35
Page has been successfully fetched! Aphelandra
Next: 36
Page has been successfully fetched! Aramaki
Next: 37
Page has been successfully fetched! Aremo_Ganmi
Next: 38
Page has been successfully fetched! Arlong
Next: 39
Page has been successfully fetched! Tsumegeri_Guards
Next: 40
Page has been successfully fetched! Arthur
Next: 41
Page has been successfully fetched! Aruyutayan_V
Next: 42
Page has been successfully fetched! Asahija
Next: 43
Page has been successfully fetched! Asashichi
Next: 44
Page has been successfully fetched! Ashura_Doji
Next: 45
Page has been successfully fetched! Asla
Next: 46
Page has been successfully fetched! Aswa
Next: 47
Page has been successfully fetched! Atagoyama
Next: 48
Page has been successfully fetched! Atlas
Next: 49
Page has been successfully fetched! Atmos
Next: 50
Page has been successfully fetched! Attach
Next: 51
Page has been successfully fetched! Avalo_Pizarro
Next: 52
Page has been successfully fetched! Ayes%C3%A9_Mar
Next: 53
Page has been successfully fetched! Azuki
Next: 54
Page has been successfully fetched! Babanuki
Next: 55
Page has been successfully fetched! Babe
Next: 56
Page has been successfully fetched! Baburu
Next: 57
Page has been successfully fetched! Baby_5
Next: 58
Page has been successfully fetched! Bacura
Next: 59
Page has been successfully fetched! Baggaley
Next: 60
Page has been successfully fetched! Bakezo
Next: 61
Page has been successfully fetched! Ban_Dedessin%C3%A9e
Next: 62
Page has been successfully fetched! Banchi
Next: 63
Page has been successfully fetched! Banchina
Next: 64
Page has been successfully fetched! Bankuro
Next: 65
Page has been successfully fetched! Banshee
Next: 66
Page has been successfully fetched! Banzaburo
Next: 67
Page has been successfully fetched! Gyoro,_Nin,_and_Bao
Next: 68
Page has been successfully fetched! Bao_Huang
Next: 69
Page has been successfully fetched! Barbel
Next: 70
Page has been successfully fetched! Bariete
Next: 71
Page has been successfully fetched! Tsumegeri_Guards
Next: 40
Page has been successfully fetched! Barry
Next: 73
Page has been successfully fetched! Bartholomew_Kuma
Next: 74
Page has been successfully fetched! Bartolomeo
Next: 75
Page has been successfully fetched! Baskerville
Next: 30
Page has been successfully fetched! Basil_Hawkins
Next: 77
Page has been successfully fetched! Basilisk
Next: 78
Page has been successfully fetched! Bastille
Next: 79
Page has been successfully fetched! Batchee
Next: 80
Page has been successfully fetched! Batman
Next: 81
Page has been successfully fetched! Battaman
Next: 82
Page has been successfully fetched! Baxcon
Next: 83
Page has been successfully fetched! Beak_Remark
Next: 84
Page has been successfully fetched! Beegirl
Next: 85
Page has been successfully fetched! Beer_VI
Next: 86
Page has been successfully fetched! Beetleman
Next: 87
Page has been successfully fetched! Bekori
Next: 88
Page has been successfully fetched! Belo_Betty
Next: 89
Page has been successfully fetched! Belladonna
Next: 90
Page has been successfully fetched! Bellamy
Next: 91
Page has been successfully fetched! Bellett
Next: 92
Page has been successfully fetched! Bell-m%C3%A8re
Next: 93
Page has been successfully fetched! Benn_Beckman
Next: 94
Page has been successfully fetched! Bent
Next: 95
Page has been successfully fetched! Bentham
Next: 96
Page has been successfully fetched! Bepo
Next: 97
Page has been successfully fetched! Bian
Next: 98
Page has been successfully fetched! Biblo
Next: 99
Page has been successfully fetched! Big_Pan
Next: 100
Page has been successfully fetched! Billy_(Pirate)
Next: 101
Page has been successfully fetched! Billy_the_Yabuki
Next: 102
Page has been successfully fetched! Bimine
Next: 103
Page has been successfully fetched! Bingo
Next: 104
Page has been successfully fetched! Birdy
Next: 105
Page has been successfully fetched! Bishamon
Next: 106
Page has been successfully fetched! Bishonure-Onna
Next: 107
Page has been successfully fetched! Bisley
Next: 108
Page has been successfully fetched! Biyo
Next: 109
Page has been successfully fetched! Bizarre
Next: 110
Page has been successfully fetched! Bjorn_(Pirate)
Next: 111
Page has been successfully fetched! Bjorn
Next: 112
Page has been successfully fetched! Black_Maria
Next: 113
Page has been successfully fetched! Blackback
Next: 114
Page has been successfully fetched! Blade
Next: 115
Page has been successfully fetched! Blakey
Next: 116
Page has been successfully fetched! Blamenco
Next: 117
Page has been successfully fetched! Blenheim
Next: 118
Page has been successfully fetched! Blondie
Next: 119
Page has been successfully fetched! Blue_Fan
Next: 120
Page has been successfully fetched! Blue_Gilly
Next: 121
Page has been successfully fetched! Bluegrass
Next: 122
Page has been successfully fetched! Bluejam
Next: 123
Page has been successfully fetched! Blueno
Next: 124
Page has been successfully fetched! Blumarine
Next: 125
Page has been successfully fetched! Boa_Hancock
Next: 126
Page has been successfully fetched! Boa_Marigold
Next: 127
Page has been successfully fetched! Boa_Sandersonia
Next: 128
Page has been successfully fetched! Bobbin
Next: 129
Page has been successfully fetched! Bobby_Funk
Next: 130
Page has been successfully fetched! Bobomba
Next: 131
Page has been successfully fetched! Bogard
Next: 132
Page has been successfully fetched! Bomba_(Marine)
Next: 133
Page has been successfully fetched! Bomba
Next: 134
Page has been successfully fetched! Bongo
Next: 135
Page has been successfully fetched! Bonk_Punch
Next: 136
Page has been successfully fetched! Boo
Next: 137
Page has been successfully fetched! Boodle
Next: 138
Page has been successfully fetched! Boogie
Next: 139
Page has been successfully fetched! Borsalino
Next: 140
Page has been successfully fetched! Super_Spot-Billed_Duck_Troops
Next: 141
Page has been successfully fetched! Braham
Next: 142
Page has been successfully fetched! Tsumegeri_Guards
Next: 40
Page has been successfully fetched! Brannew
Next: 144
Page has been successfully fetched! Brew
Next: 145
Page has been successfully fetched! Briscola
Next: 146
Page has been successfully fetched! Brocca
Next: 147
Page has been successfully fetched! Brogy
Next: 148
Page has been successfully fetched! Brontosaurus
Next: 149
Page has been successfully fetched! Brook
Next: 150
Page has been successfully fetched! Bubblegum
Next: 151
Page has been successfully fetched! Buche
Next: 152
Page has been successfully fetched! Buchi
Next: 153
Page has been successfully fetched! Buckingham_Stussy
Next: 154
Page has been successfully fetched! Buffalo
Next: 155
Page has been successfully fetched! Buggy
Next: 156
Page has been successfully fetched! Buhichuck
Next: 157
Page has been successfully fetched! Building_Snake
Next: 158
Page has been successfully fetched! Bulldog
Next: 159
Page has been successfully fetched! Bunbuku
Next: 160
Page has been successfully fetched! Bungo
Next: 161
Page has been successfully fetched! Bunny_Joe
Next: 162
Page has been successfully fetched! Bushon
Next: 163
Page has been successfully fetched! Busshiri
Next: 164
Page has been successfully fetched! Byron
Next: 165
Page has been successfully fetched! Cabaji
Next: 166
Page has been successfully fetched! Caesar_Clown
Next: 167
Page has been successfully fetched! Caimanlady
Next: 168
Page has been successfully fetched! Camie
Next: 169
Page has been successfully fetched! Camel
Next: 170
Page has been successfully fetched! Cancer
Next: 171
Page has been successfully fetched! Candre
Next: 172
Page has been successfully fetched! Cands
Next: 173
Page has been successfully fetched! Candy
Next: 174
Page has been successfully fetched! Capone_Bege
Next: 175
Page has been successfully fetched! Capone_Pez
Next: 176
Page has been successfully fetched! Capote
Next: 177
Page has been successfully fetched! Caribou
Next: 178
Page has been successfully fetched! Carmel
Next: 179
Page has been successfully fetched! Carne
Next: 180
Page has been successfully fetched! Carrot
Next: 181
Page has been successfully fetched! Catacombo
Next: 182
Page has been successfully fetched! Catarina_Devon
Next: 183
Page has been successfully fetched! Caucasusman
Next: 184
Page has been successfully fetched! Cavendish
Next: 185
Page has been successfully fetched! CB_Gallant
Next: 186
Page has been successfully fetched! Cerberus
Next: 187
Page has been successfully fetched! Cerberus_(Sword)
Next: 188
Page has been successfully fetched! Cezar
Next: 189
Page has been successfully fetched! Chabo
Next: 190
Page has been successfully fetched! Chadros_Higelyges
Next: 191
Page has been successfully fetched! Chaka
Next: 192
Page has been successfully fetched! Chao
Next: 193
Page has been successfully fetched! Chap
Next: 194
Page has been successfully fetched! Chappe
Next: 195
Page has been successfully fetched! Charlotte_Akimeg
Next: 196
Page has been successfully fetched! Charlotte_Allmeg
Next: 197
Page has been successfully fetched! Charlotte_Amande
Next: 198
Page has been successfully fetched! Charlotte_Anana
Next: 199
Page has been successfully fetched! Charlotte_Angel
Next: 200
Page has been successfully fetched! Charlotte_Anglais
Next: 201
Page has been successfully fetched! Charlotte_Basans
Next: 202
Page has been successfully fetched! Charlotte_Basskarte
Next: 203
Page has been successfully fetched! Charlotte_Bavarois
Next: 204
Page has been successfully fetched! Charlotte_Brownie
Next: 205
Page has been successfully fetched! Charlotte_Broy%C3%A9
Next: 206
Page has been successfully fetched! Charlotte_Br%C3%BBl%C3%A9e
Next: 207
Page has been successfully fetched! Charlotte_Cabaletta
Next: 208
Page has been successfully fetched! Charlotte_Cadenza
Next: 209
Page has been successfully fetched! Charlotte_Chiboust
Next: 210
Page has been successfully fetched! Charlotte_Chiffon
Next: 211
Page has been successfully fetched! Charlotte_Cinnamon
Next: 212
Page has been successfully fetched! Charlotte_Citron
Next: 213
Page has been successfully fetched! Charlotte_Compo
Next: 214
Page has been successfully fetched! Charlotte_Compote
Next: 215
Page has been successfully fetched! Charlotte_Cornstarch
Next: 216
Page has been successfully fetched! Charlotte_Counter
Next: 217
Page has been successfully fetched! Charlotte_Cracker
Next: 218
Page has been successfully fetched! Charlotte_Custard
Next: 219
Page has been successfully fetched! Charlotte_Dacquoise
Next: 220
Page has been successfully fetched! Charlotte_Daifuku
Next: 221
Page has been successfully fetched! Charlotte_De-Chat
Next: 222
Page has been successfully fetched! Charlotte_Dolce_and_Drag%C3%A9e
Next: 223
Page has been successfully fetched! Charlotte_Dosmarche
Next: 224
Page has been successfully fetched! Charlotte_Dolce_and_Drag%C3%A9e
Next: 223
Page has been successfully fetched! Charlotte_Effil%C3%A9e
Next: 226
Page has been successfully fetched! Charlotte_Flampe
Next: 227
Page has been successfully fetched! Charlotte_Fuyumeg
Next: 228
Page has been successfully fetched! Charlotte_Gala
Next: 229
Page has been successfully fetched! Charlotte_Galette
Next: 230
Page has been successfully fetched! Charlotte_Hach%C3%A9e
Next: 231
Page has been successfully fetched! Charlotte_Harumeg
Next: 232
Page has been successfully fetched! Charlotte_High-Fat
Next: 233
Page has been successfully fetched! Charlotte_Joconde
Next: 234
Page has been successfully fetched! Charlotte_Joscarpone
Next: 235
Page has been successfully fetched! Charlotte_Kanten
Next: 236
Page has been successfully fetched! Charlotte_Katakuri
Next: 237
Page has been successfully fetched! Charlotte_Kato
Next: 238
Page has been successfully fetched! Charlotte_Laurin
Next: 239
Page has been successfully fetched! Charlotte_Linlin
Next: 240
Page has been successfully fetched! Charlotte_Lola
Next: 241
Page has been successfully fetched! Charlotte_Maple
Next: 242
Page has been successfully fetched! Charlotte_Marble
Next: 243
Page has been successfully fetched! Charlotte_Marnier
Next: 244
Page has been successfully fetched! Charlotte_Mascarpone
Next: 245
Page has been successfully fetched! Charlotte_Mash
Next: 246
Page has been successfully fetched! Charlotte_Melise
Next: 247
Page has been successfully fetched! Charlotte_Mobile
Next: 248
Page has been successfully fetched! Charlotte_Mond%C3%A9e
Next: 249
Page has been successfully fetched! Charlotte_Mont-d%27Or
Next: 250
Page has been successfully fetched! Charlotte_Montb
Next: 251
Page has been successfully fetched! Charlotte_Moscato
Next: 252
Page has been successfully fetched! Charlotte_Mozart
Next: 253
Page has been successfully fetched! Charlotte_Myukuru
Next: 254
Page has been successfully fetched! Charlotte_Decuplets
Next: 255
Page has been successfully fetched! Charlotte_Decuplets
Next: 255
Page has been successfully fetched! Charlotte_Decuplets
Next: 255
Page has been successfully fetched! Charlotte_Decuplets
Next: 255
Page has been successfully fetched! Charlotte_Newshi
Next: 259
Page has been successfully fetched! Charlotte_Noisette
Next: 260
Page has been successfully fetched! Charlotte_Normande
Next: 261
Page has been successfully fetched! Charlotte_Nougat
Next: 262
Page has been successfully fetched! Charlotte_Nusstorte
Next: 263
Page has been successfully fetched! Charlotte_Nutmeg
Next: 264
Page has been successfully fetched! Charlotte_Opera
Next: 265
Page has been successfully fetched! Charlotte_Oven
Next: 266
Page has been successfully fetched! Charlotte_Panna
Next: 267
Page has been successfully fetched! Charlotte_Perospero
Next: 268
Page has been successfully fetched! Charlotte_Poire
Next: 269
Page has been successfully fetched! Charlotte_Praline
Next: 270
Page has been successfully fetched! Charlotte_Prim
Next: 271
Page has been successfully fetched! Charlotte_Pudding
Next: 272
Page has been successfully fetched! Charlotte_Raisin
Next: 273
Page has been successfully fetched! Charlotte_Saint-Marc
Next: 274
Page has been successfully fetched! Charlotte_Smoothie
Next: 275
Page has been successfully fetched! Charlotte_Snack
Next: 276
Page has been successfully fetched! Charlotte_Tablet
Next: 277
Page has been successfully fetched! Charlotte_Wafers
Next: 278
Page has been successfully fetched! Charlotte_Wiro
Next: 279
Page has been successfully fetched! Charlotte_Yuen
Next: 280
Page has been successfully fetched! Charlotte_Zuccotto
Next: 281
Page has been successfully fetched! Chess
Next: 282
Page has been successfully fetched! Chesskippa
Next: 283
Page has been successfully fetched! Chessmarimo
Next: 284
Page has been successfully fetched! Chew
Next: 285
Page has been successfully fetched! Chichilisia
Next: 286
Page has been successfully fetched! Chicken
Next: 287
Page has been successfully fetched! Chicory
Next: 288
Page has been successfully fetched! Chimney
Next: 289
Page has been successfully fetched! Chinjao
Next: 290
Page has been successfully fetched! Chihaya
Next: 291
Page has been successfully fetched! Chiya
Next: 292
Page has been successfully fetched! Cho
Next: 293
Page has been successfully fetched! Chochinman
Next: 294
Page has been successfully fetched! Chocho
Next: 295
Page has been successfully fetched! Choco_Police
Next: 296
Page has been successfully fetched! Chocolat
Next: 297
Page has been successfully fetched! Choi
Next: 298
Page has been successfully fetched! Chokyumei-no_Chosuke
Next: 299
Page has been successfully fetched! Chome
Next: 300
Page has been successfully fetched! Chouchou
Next: 301
Page has been successfully fetched! Chuchun
Next: 302
Page has been successfully fetched! Chuji
Next: 303
Page has been successfully fetched! Clapp
Next: 304
Page has been successfully fetched! Clione
Next: 305
Page has been successfully fetched! Clou_D._Clover
Next: 306
Page has been successfully fetched! Coburn
Next: 307
Page has been successfully fetched! Cocoa
Next: 308
Page has been successfully fetched! Cocox
Next: 309
Page has been successfully fetched! Colon
Next: 310
Page has been successfully fetched! Colscon
Next: 311
Page has been successfully fetched! Columbus
Next: 312
Page has been successfully fetched! Comil
Next: 313
Page has been successfully fetched! Compo
Next: 314
Page has been successfully fetched! Concelot
Next: 315
Page has been successfully fetched! Conis
Next: 316
Page has been successfully fetched! Conney
Next: 317
Page has been successfully fetched! Corgi
Next: 318
Page has been successfully fetched! Coribou
Next: 319
Page has been successfully fetched! Cornelia
Next: 320
Page has been successfully fetched! Cosette
Next: 321
Page has been successfully fetched! Cosmo
Next: 322
Page has been successfully fetched! Cosmos
Next: 323
Page has been successfully fetched! Cotton
Next: 324
Page has been successfully fetched! Couran
Next: 325
Page has been successfully fetched! Cowboy
Next: 326
Page has been successfully fetched! Crocodile
Next: 327
Page has been successfully fetched! Crocus
Next: 328
Page has been successfully fetched! Curiel
Next: 329
Page has been successfully fetched! Curly_Dadan
Next: 330
Page has been successfully fetched! Cyrano
Next: 331
Page has been successfully fetched! D.R.
Next: 332
Page has been successfully fetched! Dachoman
Next: 333
Page has been successfully fetched! Daddy_Dee
Next: 334
Page has been successfully fetched! Dagama
Next: 335
Page has been successfully fetched! Dago
Next: 336
Page has been successfully fetched! Daidalos
Next: 337
Page has been successfully fetched! Daifugo
Next: 338
Page has been successfully fetched! Daigin
Next: 339
Page has been successfully fetched! Daikoku
Next: 340
Page has been successfully fetched! Daikon
Next: 341
Page has been successfully fetched! Daisy
Next: 342
Page has been successfully fetched! Dalmatian
Next: 343
Page has been successfully fetched! Dalton
Next: 344
Page has been successfully fetched! Damask
Next: 345
Page has been successfully fetched! Daruma
Next: 346
Page has been successfully fetched! Dashiteyaro
Next: 347
Page has been successfully fetched! Davy_D._Jones
Next: 348
Page has been successfully fetched! Daz_Bonez
Next: 349
Page has been successfully fetched! Decalvan_Brothers
Next: 350
Page has been successfully fetched! Deigoro
Next: 351

In [14]:
character_info = pd.DataFrame(character_info_list)
character_info.head()

character_info.to_csv('character_info_v2.csv')

In [48]:
len(character_info)

1555

# Chapter Scraping

In [51]:
cover_pattern = r'\(cover\)'
cover_regex = re.compile(cover_pattern)

flashback_pattern = r'\(flashback\)'
flashback_regex = re.compile(flashback_pattern)

recent_chapter = 1176

In [52]:
chapter_character_dataframe = char_table[['name']].copy(deep=True).set_index('name')

for i in range(1,recent_chapter+1):
    chapter_character_dataframe[str(i)] = 0

/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0
/tmp/ipykernel_11354/1725584858.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_character_dataframe[str(i)] = 0

In [53]:
chapter_character_dataframe

,1,2,3,4,5,6,7,8,9,10,...,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176
name,,,,,,,,,,,,,,,,,,,,,
A O,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Abdullah,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Absalom,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Acilia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Adele,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zodia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zotto,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zucca,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zunesha,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zururin,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [116]:
character_scraped_df = pd.read_csv('character_info_v2.csv')

In [55]:
import ast
import itertools

In [56]:
affiliation_pattern = r'\(.*?\)'
affiliation_regex = re.compile(affiliation_pattern)

weird_pattern = r'\xa0‡'
weird_regex = re.compile(weird_pattern)

In [57]:
affiliations = [i.strip() for i in list(itertools.chain.from_iterable([ast.literal_eval(i) for i in character_scraped_df['Affiliations'].dropna().to_list()]))]
stripped_affiliations = []
for i in affiliations:
    stripped_affiliations.append(affiliation_regex.sub('', i).strip()) 

affiliations_list = list(set(stripped_affiliations))

In [58]:
chapter_affiliations_dataframe = pd.DataFrame(affiliations_list, columns=['Affiliation']).set_index('Affiliation')

for i in range(1,recent_chapter+1):
    chapter_affiliations_dataframe[str(i)] = 0

/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0
/tmp/ipykernel_11354/3553183193.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  chapter_affiliations_dataframe[str(i)] = 0

In [59]:
chapter_affiliations_dataframe

,1,2,3,4,5,6,7,8,9,10,...,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176
Affiliation,,,,,,,,,,,,,,,,,,,,,
Caesar Clown,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Wapol,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Pacifista,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Laboon,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Guardians,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
G-1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Tontatta Pirates,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Gol D. Roger,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Will of D.,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Sea Floor,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [83]:
for chapter in range(1,recent_chapter+1):
    chapter_page = fetch_onepiece(f"Chapter_{chapter}")
    chapter_soup = BeautifulSoup(chapter_page, 'html5lib')

    chapter_characters = [i.text for i in chapter_soup.find(class_='CharTable').find_all('li')]
    present_characters = []
    for i in chapter_characters:
        if not (cover_regex.findall(i) or flashback_regex.findall(i)):
            present_characters.append(i)
    for i in present_characters:
        if i in char_table['name'].to_list():
            chapter_character_dataframe.at[i, str(chapter)] = 1

    # chapter_affiliations = [i.text for i in chapter_soup.find(class_='CharTable').find_all('dt')]
    # present_affiliations = []
    # for i in chapter_affiliations:
    #     if not (cover_regex.findall(i) or flashback_regex.findall(i)):
    #         present_affiliations.append(i)
    # for i in present_affiliations:
    #     if i in affiliations_list:
    #         chapter_affiliations_dataframe.at[i, str(chapter)] = 1

Page has been successfully fetched! Chapter_1
Page has been successfully fetched! Chapter_2
Page has been successfully fetched! Chapter_3
Page has been successfully fetched! Chapter_4
Page has been successfully fetched! Chapter_5
Page has been successfully fetched! Chapter_6
Page has been successfully fetched! Chapter_7
Page has been successfully fetched! Chapter_8
Page has been successfully fetched! Chapter_9
Page has been successfully fetched! Chapter_10
Page has been successfully fetched! Chapter_11
Page has been successfully fetched! Chapter_12
Page has been successfully fetched! Chapter_13
Page has been successfully fetched! Chapter_14
Page has been successfully fetched! Chapter_15
Page has been successfully fetched! Chapter_16
Page has been successfully fetched! Chapter_17
Page has been successfully fetched! Chapter_18
Page has been successfully fetched! Chapter_19
Page has been successfully fetched! Chapter_20
Page has been successfully fetched! Chapter_21
Page has been successfully fetched! Chapter_22
Page has been successfully fetched! Chapter_23
Page has been successfully fetched! Chapter_24
Page has been successfully fetched! Chapter_25
Page has been successfully fetched! Chapter_26
Page has been successfully fetched! Chapter_27
Page has been successfully fetched! Chapter_28
Page has been successfully fetched! Chapter_29
Page has been successfully fetched! Chapter_30
Page has been successfully fetched! Chapter_31
Page has been successfully fetched! Chapter_32
Page has been successfully fetched! Chapter_33
Page has been successfully fetched! Chapter_34
Page has been successfully fetched! Chapter_35
Page has been successfully fetched! Chapter_36
Page has been successfully fetched! Chapter_37
Page has been successfully fetched! Chapter_38
Page has been successfully fetched! Chapter_39
Page has been successfully fetched! Chapter_40
Page has been successfully fetched! Chapter_41
Page has been successfully fetched! Chapter_42
Page has been successfully fetched! Chapter_43
Page has been successfully fetched! Chapter_44
Page has been successfully fetched! Chapter_45
Page has been successfully fetched! Chapter_46
Page has been successfully fetched! Chapter_47
Page has been successfully fetched! Chapter_48
Page has been successfully fetched! Chapter_49
Page has been successfully fetched! Chapter_50
Page has been successfully fetched! Chapter_51
Page has been successfully fetched! Chapter_52
Page has been successfully fetched! Chapter_53
Page has been successfully fetched! Chapter_54
Page has been successfully fetched! Chapter_55
Page has been successfully fetched! Chapter_56
Page has been successfully fetched! Chapter_57
Page has been successfully fetched! Chapter_58
Page has been successfully fetched! Chapter_59
Page has been successfully fetched! Chapter_60
Page has been successfully fetched! Chapter_61
Page has been successfully fetched! Chapter_62
Page has been successfully fetched! Chapter_63
Page has been successfully fetched! Chapter_64
Page has been successfully fetched! Chapter_65
Page has been successfully fetched! Chapter_66
Page has been successfully fetched! Chapter_67
Page has been successfully fetched! Chapter_68
Page has been successfully fetched! Chapter_69
Page has been successfully fetched! Chapter_70
Page has been successfully fetched! Chapter_71
Page has been successfully fetched! Chapter_72
Page has been successfully fetched! Chapter_73
Page has been successfully fetched! Chapter_74
Page has been successfully fetched! Chapter_75
Page has been successfully fetched! Chapter_76
Page has been successfully fetched! Chapter_77
Page has been successfully fetched! Chapter_78
Page has been successfully fetched! Chapter_79
Page has been successfully fetched! Chapter_80
Page has been successfully fetched! Chapter_81
Page has been successfully fetched! Chapter_82
Page has been successfully fetched! Chapter_83
Page has been successfully fetched! Chapter_84
Page has been successfully fetched! Chapter_85
Page has been successfully fetched! Chapter_86
Page has been successfully fetched! Chapter_87
Page has been successfully fetched! Chapter_88
Page has been successfully fetched! Chapter_89
Page has been successfully fetched! Chapter_90
Page has been successfully fetched! Chapter_91
Page has been successfully fetched! Chapter_92
Page has been successfully fetched! Chapter_93
Page has been successfully fetched! Chapter_94
Page has been successfully fetched! Chapter_95
Page has been successfully fetched! Chapter_96
Page has been successfully fetched! Chapter_97
Page has been successfully fetched! Chapter_98
Page has been successfully fetched! Chapter_99
Page has been successfully fetched! Chapter_100
Page has been successfully fetched! Chapter_101
Page has been successfully fetched! Chapter_102
Page has been successfully fetched! Chapter_103
Page has been successfully fetched! Chapter_104
Page has been successfully fetched! Chapter_105
Page has been successfully fetched! Chapter_106
Page has been successfully fetched! Chapter_107
Page has been successfully fetched! Chapter_108
Page has been successfully fetched! Chapter_109
Page has been successfully fetched! Chapter_110
Page has been successfully fetched! Chapter_111
Page has been successfully fetched! Chapter_112
Page has been successfully fetched! Chapter_113
Page has been successfully fetched! Chapter_114
Page has been successfully fetched! Chapter_115
Page has been successfully fetched! Chapter_116
Page has been successfully fetched! Chapter_117
Page has been successfully fetched! Chapter_118
Page has been successfully fetched! Chapter_119
Page has been successfully fetched! Chapter_120
Page has been successfully fetched! Chapter_121
Page has been successfully fetched! Chapter_122
Page has been successfully fetched! Chapter_123
Page has been successfully fetched! Chapter_124
Page has been successfully fetched! Chapter_125
Page has been successfully fetched! Chapter_126
Page has been successfully fetched! Chapter_127
Page has been successfully fetched! Chapter_128
Page has been successfully fetched! Chapter_129
Page has been successfully fetched! Chapter_130
Page has been successfully fetched! Chapter_131
Page has been successfully fetched! Chapter_132
Page has been successfully fetched! Chapter_133
Page has been successfully fetched! Chapter_134
Page has been successfully fetched! Chapter_135
Page has been successfully fetched! Chapter_136
Page has been successfully fetched! Chapter_137
Page has been successfully fetched! Chapter_138
Page has been successfully fetched! Chapter_139
Page has been successfully fetched! Chapter_140
Page has been successfully fetched! Chapter_141
Page has been successfully fetched! Chapter_142
Page has been successfully fetched! Chapter_143
Page has been successfully fetched! Chapter_144
Page has been successfully fetched! Chapter_145
Page has been successfully fetched! Chapter_146
Page has been successfully fetched! Chapter_147
Page has been successfully fetched! Chapter_148
Page has been successfully fetched! Chapter_149
Page has been successfully fetched! Chapter_150
Page has been successfully fetched! Chapter_151
Page has been successfully fetched! Chapter_152
Page has been successfully fetched! Chapter_153
Page has been successfully fetched! Chapter_154
Page has been successfully fetched! Chapter_155
Page has been successfully fetched! Chapter_156
Page has been successfully fetched! Chapter_157
Page has been successfully fetched! Chapter_158
Page has been successfully fetched! Chapter_159
Page has been successfully fetched! Chapter_160
Page has been successfully fetched! Chapter_161
Page has been successfully fetched! Chapter_162
Page has been successfully fetched! Chapter_163
Page has been successfully fetched! Chapter_164
Page has been successfully fetched! Chapter_165
Page has been successfully fetched! Chapter_166
Page has been successfully fetched! Chapter_167
Page has been successfully fetched! Chapter_168
Page has been successfully fetched! Chapter_169
Page has been successfully fetched! Chapter_170
Page has been successfully fetched! Chapter_171
Page has been successfully fetched! Chapter_172
Page has been successfully fetched! Chapter_173
Page has been successfully fetched! Chapter_174
Page has been successfully fetched! Chapter_175
Page has been successfully fetched! Chapter_176
Page has been successfully fetched! Chapter_177
Page has been successfully fetched! Chapter_178
Page has been successfully fetched! Chapter_179
Page has been successfully fetched! Chapter_180
Page has been successfully fetched! Chapter_181
Page has been successfully fetched! Chapter_182
Page has been successfully fetched! Chapter_183
Page has been successfully fetched! Chapter_184
Page has been successfully fetched! Chapter_185
Page has been successfully fetched! Chapter_186
Page has been successfully fetched! Chapter_187
Page has been successfully fetched! Chapter_188
Page has been successfully fetched! Chapter_189
Page has been successfully fetched! Chapter_190
Page has been successfully fetched! Chapter_191
Page has been successfully fetched! Chapter_192
Page has been successfully fetched! Chapter_193
Page has been successfully fetched! Chapter_194
Page has been successfully fetched! Chapter_195
Page has been successfully fetched! Chapter_196
Page has been successfully fetched! Chapter_197
Page has been successfully fetched! Chapter_198
Page has been successfully fetched! Chapter_199
Page has been successfully fetched! Chapter_200
Page has been successfully fetched! Chapter_201
Page has been successfully fetched! Chapter_202
Page has been successfully fetched! Chapter_203
Page has been successfully fetched! Chapter_204
Page has been successfully fetched! Chapter_205
Page has been successfully fetched! Chapter_206
Page has been successfully fetched! Chapter_207
Page has been successfully fetched! Chapter_208
Page has been successfully fetched! Chapter_209
Page has been successfully fetched! Chapter_210
Page has been successfully fetched! Chapter_211
Page has been successfully fetched! Chapter_212
Page has been successfully fetched! Chapter_213
Page has been successfully fetched! Chapter_214
Page has been successfully fetched! Chapter_215
Page has been successfully fetched! Chapter_216
Page has been successfully fetched! Chapter_217
Page has been successfully fetched! Chapter_218
Page has been successfully fetched! Chapter_219
Page has been successfully fetched! Chapter_220
Page has been successfully fetched! Chapter_221
Page has been successfully fetched! Chapter_222
Page has been successfully fetched! Chapter_223
Page has been successfully fetched! Chapter_224
Page has been successfully fetched! Chapter_225
Page has been successfully fetched! Chapter_226
Page has been successfully fetched! Chapter_227
Page has been successfully fetched! Chapter_228
Page has been successfully fetched! Chapter_229
Page has been successfully fetched! Chapter_230
Page has been successfully fetched! Chapter_231
Page has been successfully fetched! Chapter_232
Page has been successfully fetched! Chapter_233
Page has been successfully fetched! Chapter_234
Page has been successfully fetched! Chapter_235
Page has been successfully fetched! Chapter_236
Page has been successfully fetched! Chapter_237
Page has been successfully fetched! Chapter_238
Page has been successfully fetched! Chapter_239
Page has been successfully fetched! Chapter_240
Page has been successfully fetched! Chapter_241
Page has been successfully fetched! Chapter_242
Page has been successfully fetched! Chapter_243
Page has been successfully fetched! Chapter_244
Page has been successfully fetched! Chapter_245
Page has been successfully fetched! Chapter_246
Page has been successfully fetched! Chapter_247
Page has been successfully fetched! Chapter_248
Page has been successfully fetched! Chapter_249
Page has been successfully fetched! Chapter_250
Page has been successfully fetched! Chapter_251
Page has been successfully fetched! Chapter_252
Page has been successfully fetched! Chapter_253
Page has been successfully fetched! Chapter_254
Page has been successfully fetched! Chapter_255
Page has been successfully fetched! Chapter_256
Page has been successfully fetched! Chapter_257
Page has been successfully fetched! Chapter_258
Page has been successfully fetched! Chapter_259
Page has been successfully fetched! Chapter_260
Page has been successfully fetched! Chapter_261
Page has been successfully fetched! Chapter_262
Page has been successfully fetched! Chapter_263
Page has been successfully fetched! Chapter_264
Page has been successfully fetched! Chapter_265
Page has been successfully fetched! Chapter_266
Page has been successfully fetched! Chapter_267
Page has been successfully fetched! Chapter_268
Page has been successfully fetched! Chapter_269
Page has been successfully fetched! Chapter_270
Page has been successfully fetched! Chapter_271
Page has been successfully fetched! Chapter_272
Page has been successfully fetched! Chapter_273
Page has been successfully fetched! Chapter_274
Page has been successfully fetched! Chapter_275
Page has been successfully fetched! Chapter_276
Page has been successfully fetched! Chapter_277
Page has been successfully fetched! Chapter_278
Page has been successfully fetched! Chapter_279
Page has been successfully fetched! Chapter_280
Page has been successfully fetched! Chapter_281
Page has been successfully fetched! Chapter_282
Page has been successfully fetched! Chapter_283
Page has been successfully fetched! Chapter_284
Page has been successfully fetched! Chapter_285
Page has been successfully fetched! Chapter_286
Page has been successfully fetched! Chapter_287
Page has been successfully fetched! Chapter_288
Page has been successfully fetched! Chapter_289
Page has been successfully fetched! Chapter_290
Page has been successfully fetched! Chapter_291
Page has been successfully fetched! Chapter_292
Page has been successfully fetched! Chapter_293
Page has been successfully fetched! Chapter_294
Page has been successfully fetched! Chapter_295
Page has been successfully fetched! Chapter_296
Page has been successfully fetched! Chapter_297
Page has been successfully fetched! Chapter_298
Page has been successfully fetched! Chapter_299
Page has been successfully fetched! Chapter_300
Page has been successfully fetched! Chapter_301
Page has been successfully fetched! Chapter_302
Page has been successfully fetched! Chapter_303
Page has been successfully fetched! Chapter_304
Page has been successfully fetched! Chapter_305
Page has been successfully fetched! Chapter_306
Page has been successfully fetched! Chapter_307
Page has been successfully fetched! Chapter_308
Page has been successfully fetched! Chapter_309
Page has been successfully fetched! Chapter_310
Page has been successfully fetched! Chapter_311
Page has been successfully fetched! Chapter_312
Page has been successfully fetched! Chapter_313
Page has been successfully fetched! Chapter_314
Page has been successfully fetched! Chapter_315
Page has been successfully fetched! Chapter_316
Page has been successfully fetched! Chapter_317
Page has been successfully fetched! Chapter_318
Page has been successfully fetched! Chapter_319
Page has been successfully fetched! Chapter_320
Page has been successfully fetched! Chapter_321
Page has been successfully fetched! Chapter_322
Page has been successfully fetched! Chapter_323
Page has been successfully fetched! Chapter_324
Page has been successfully fetched! Chapter_325
Page has been successfully fetched! Chapter_326
Page has been successfully fetched! Chapter_327
Page has been successfully fetched! Chapter_328
Page has been successfully fetched! Chapter_329
Page has been successfully fetched! Chapter_330
Page has been successfully fetched! Chapter_331
Page has been successfully fetched! Chapter_332
Page has been successfully fetched! Chapter_333
Page has been successfully fetched! Chapter_334
Page has been successfully fetched! Chapter_335
Page has been successfully fetched! Chapter_336
Page has been successfully fetched! Chapter_337
Page has been successfully fetched! Chapter_338
Page has been successfully fetched! Chapter_339
Page has been successfully fetched! Chapter_340
Page has been successfully fetched! Chapter_341
Page has been successfully fetched! Chapter_342
Page has been successfully fetched! Chapter_343
Page has been successfully fetched! Chapter_344
Page has been successfully fetched! Chapter_345
Page has been successfully fetched! Chapter_346
Page has been successfully fetched! Chapter_347
Page has been successfully fetched! Chapter_348
Page has been successfully fetched! Chapter_349
Page has been successfully fetched! Chapter_350
Page has been successfully fetched! Chapter_351
Page has been successfully fetched! Chapter_352
Page has been successfully fetched! Chapter_353
Page has been successfully fetched! Chapter_354
Page has been successfully fetched! Chapter_355
Page has been successfully fetched! Chapter_356
Page has been successfully fetched! Chapter_357
Page has been successfully fetched! Chapter_358
Page has been successfully fetched! Chapter_359
Page has been successfully fetched! Chapter_360
Page has been successfully fetched! Chapter_361
Page has been successfully fetched! Chapter_362
Page has been successfully fetched! Chapter_363
Page has been successfully fetched! Chapter_364
Page has been successfully fetched! Chapter_365
Page has been successfully fetched! Chapter_366
Page has been successfully fetched! Chapter_367
Page has been successfully fetched! Chapter_368
Page has been successfully fetched! Chapter_369
Page has been successfully fetched! Chapter_370
Page has been successfully fetched! Chapter_371
Page has been successfully fetched! Chapter_372
Page has been successfully fetched! Chapter_373
Page has been successfully fetched! Chapter_374
Page has been successfully fetched! Chapter_375
Page has been successfully fetched! Chapter_376
Page has been successfully fetched! Chapter_377
Page has been successfully fetched! Chapter_378
Page has been successfully fetched! Chapter_379
Page has been successfully fetched! Chapter_380
Page has been successfully fetched! Chapter_381
Page has been successfully fetched! Chapter_382
Page has been successfully fetched! Chapter_383
Page has been successfully fetched! Chapter_384
Page has been successfully fetched! Chapter_385
Page has been successfully fetched! Chapter_386
Page has been successfully fetched! Chapter_387
Page has been successfully fetched! Chapter_388
Page has been successfully fetched! Chapter_389
Page has been successfully fetched! Chapter_390
Page has been successfully fetched! Chapter_391
Page has been successfully fetched! Chapter_392
Page has been successfully fetched! Chapter_393
Page has been successfully fetched! Chapter_394
Page has been successfully fetched! Chapter_395
Page has been successfully fetched! Chapter_396
Page has been successfully fetched! Chapter_397
Page has been successfully fetched! Chapter_398
Page has been successfully fetched! Chapter_399
Page has been successfully fetched! Chapter_400
Page has been successfully fetched! Chapter_401
Page has been successfully fetched! Chapter_402
Page has been successfully fetched! Chapter_403
Page has been successfully fetched! Chapter_404
Page has been successfully fetched! Chapter_405
Page has been successfully fetched! Chapter_406
Page has been successfully fetched! Chapter_407
Page has been successfully fetched! Chapter_408
Page has been successfully fetched! Chapter_409
Page has been successfully fetched! Chapter_410
Page has been successfully fetched! Chapter_411
Page has been successfully fetched! Chapter_412
Page has been successfully fetched! Chapter_413
Page has been successfully fetched! Chapter_414
Page has been successfully fetched! Chapter_415
Page has been successfully fetched! Chapter_416
Page has been successfully fetched! Chapter_417
Page has been successfully fetched! Chapter_418

In [84]:
chapter_affiliations_dataframe[chapter_affiliations_dataframe['560']==1]

,1,2,3,4,5,6,7,8,9,10,...,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176
Affiliation,,,,,,,,,,,,,,,,,,,,,
Thriller Bark Pirates,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Kuja Pirates,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Buggy and Alvida Alliance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Whitebeard Pirates,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Straw Hat Pirates,0,0,0,0,1,1,1,1,1,1,...,0,0,0,1,1,1,1,1,1,1

In [89]:
chapter_character_dataframe.to_csv('character_appearance.csv')

In [88]:
chapter_character_dataframe[chapter_character_dataframe['562']==1]

,1,2,3,4,5,6,7,8,9,10,...,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176
name,,,,,,,,,,,,,,,,,,,,,
Bartholomew Kuma,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Blenheim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Boa Hancock,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Buggy,0,0,0,0,0,0,0,0,1,1,...,1,0,0,0,0,0,0,0,0,0
Crocodile,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Curiel,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Dracule Mihawk,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Edward Newgate,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Emporio Ivankov,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Fossa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Gecko Moria,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Haruta,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Izou,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Jinbe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,1,1
Jozu,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Kingdew,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Marco,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Monkey D. Luffy,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,1,0,0,1,1,0
Namur,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Portgas D. Ace,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Sengoku,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Sentomaru,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Smoker,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Speed Jiru,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Squard,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Tashigi,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Vista,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [81]:
"Monkey D. Luffy" in char_table['name'].to_list()

True

# Character Affiliations

In [117]:
char_affil_df = character_scraped_df[['Official English Name']].copy(deep=True).set_index('Official English Name')

for i in affiliations_list:
    char_affil_df[i] = 0

/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0
/tmp/ipykernel_11354/3304305546.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  char_affil_df[i] = 0

In [118]:
char_affil_df

,Caesar Clown,Wapol,Pacifista,Laboon,Guardians,Lulusia Kingdom,Harahettania,Drake Pirates,Bourgeois Kingdom,Portgas D. Ace,...,Ganzack Pirates,Ohara,MADS,Blackbeard Pirates,G-2,G-1,Tontatta Pirates,Gol D. Roger,Will of D.,Sea Floor
Official English Name,,,,,,,,,,,,,,,,,,,,,
A.O.,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Abdullah,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Absalom,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Agilia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Adelle,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zodia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Burr,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zukka,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zunesha,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zururin,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [137]:
for i in range(len(character_scraped_df)):
    affil = character_scraped_df['Affiliations'][i]
    if affil is np.nan:
        continue
    for j in ast.literal_eval(character_scraped_df['Affiliations'][i]):
        if j in affiliations_list:
            char_affil_df.at[character_scraped_df['Official English Name'][i], j] = 1

In [141]:
char_affil_df.to_csv('character_affiliations.csv')

In [ ]:
char_app_df = pd.read_csv('character_appearance.csv')