In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data/character_info_v2.csv')

In [5]:
character_df = df.drop([df.columns[0]], axis=1)

In [6]:
character_df[character_df['Official English Name']=='Zunesha']

,Official English Name,Debut,Affiliations,Occupations,Status,Birthday,Devil Fruit,Observation Haki,Armament Haki,Conquerers Haki,Origin,Age,Height,Blood Type,Fruit Type,Bounty
1553,Zunesha,802.0,NaN,NaN,Alive,December 18,0,0,0,0,Grand Line,1000.0,5000.0,NaN,NaN,NaN

In [7]:
character_df.loc[character_df.iloc[:, character_df.columns.get_loc('Affiliations')].str.contains('Pirates', na=False)].groupby('Affiliations').sum('Bounty')[['Bounty']].sort_values(by='Bounty', ascending=False)

ValueError: numeric_only accepts only Boolean values

In [43]:
character_df[character_df['Official English Name']=='Charlotte Katakuri']

,Official English Name,Debut,Affiliations,Occupations,Status,Birthday,Devil Fruit,Observation Haki,Armament Haki,Conquerers Haki,Origin,Age,Height,Blood Type,Fruit Type,Bounty
235,Charlotte Katakuri,860.0,Charlotte Family,Sweet Commander,Alive,November 25,1,1,1,1,Grand Line,48.0,509.0,XF,Special Paramecia,1.057000e+09

In [44]:
character_df.loc[character_df.iloc[:, character_df.columns.get_loc('Affiliations')].str.contains('Charlotte Family', na=False)]

,Official English Name,Debut,Affiliations,Occupations,Status,Birthday,Devil Fruit,Observation Haki,Armament Haki,Conquerers Haki,Origin,Age,Height,Blood Type,Fruit Type,Bounty
194,Charlotte Akimeg,894.0,Charlotte Family (Charlotte Decuplets),Pirate,Alive,December 2,0,0,0,0,NaN,18.0,NaN,NaN,NaN,NaN
195,Charlotte Allmeg,894.0,Charlotte Family (Charlotte Decuplets),Pirate,Alive,December 2,0,0,0,0,NaN,18.0,NaN,NaN,NaN,NaN
196,Charlotte Amande,827.0,Charlotte Family,Pirate Officer,Alive,December 10,0,0,0,0,NaN,47.0,NaN,NaN,NaN,0.0
197,Charlotte Anana,845.0,Charlotte Family,NaN,Alive,April 17,0,0,0,0,NaN,8.0,NaN,NaN,NaN,NaN
198,Charlotte Angel,860.0,Charlotte Family,Pirate Officer,Alive,February 28,0,0,0,0,Grand Line,45.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,Charlotte Wafers,845.0,Charlotte Family,NaN,Alive,NaN,0,0,0,0,NaN,13.0,NaN,NaN,NaN,NaN
277,Charlotte Uiro,845.0,Charlotte Family,NaN,Alive,NaN,0,0,0,0,NaN,12.0,NaN,NaN,NaN,NaN
278,Charlotte Yuen,894.0,Charlotte Family,Pirate Officer,Alive,October 15,0,0,0,0,NaN,19.0,NaN,NaN,NaN,NaN
279,Charlotte Zuccotto,862.0,Charlotte Family,Pirate Officer,Alive,NaN,0,0,0,0,NaN,44.0,NaN,NaN,NaN,NaN
1135,Pound,831.0,Charlotte Family (Former) ‡,NaN,Alive,August 21,0,0,0,0,Grand Line,48.0,731.0,F,NaN,NaN

In [40]:
character_df.loc[character_df.iloc[:, character_df.columns.get_loc('Affiliations')].str.contains('Rocks Pirates', na=False)]

,Official English Name,Debut,Affiliations,Occupations,Status,Birthday,Devil Fruit,Observation Haki,Armament Haki,Conquerers Haki,Origin,Age,Height,Blood Type,Fruit Type,Bounty
69,Barbell,1096.0,Rocks Pirates (former),Pirate,Unknown,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
152,Buckingham Stussy,802.0,Rocks Pirates (former),Pirate (former),Alive,April 12,0,0,0,0,Grand Line,76.0,68.0,S,NaN,NaN
475,Ganzui,450.0,Rocks Pirates (former),General Zombie,Deceased,NaN,1,0,0,0,NaN,NaN,NaN,NaN,Paramecia,NaN
690,John,450.0,Rocks Pirates (former),General Zombie,Deceased,NaN,1,0,0,0,NaN,NaN,NaN,NaN,Paramecia,NaN
822,Kyo,1156.0,Rocks Pirates (former),Pirate,Unknown,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
885,Marlon,1155.0,Rocks Pirates,Pirate,Deceased,NaN,0,0,0,0,West Blue,NaN,NaN,NaN,NaN,NaN
1063,Wang Zhi,1155.0,Rocks Pirates (former),Pirate Guru,Unknown,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1194,Rocks D. Xebec,957.0,Rocks Pirates,Pirate Captain,Deceased,NaN,0,0,1,1,West Blue,NaN,NaN,NaN,NaN,0.0

In [ ]:
8_816_001_000.0

In [22]:
character_df.loc[character_df.iloc[:, character_df.columns.get_loc('Status')].isin(['Deceased', 'Destroyed'])]

,Official English Name,Debut,Affiliations,Occupations,Status,Birthday,Devil Fruit,Observation Haki,Armament Haki,Conquerers Haki,Origin,Age,Height,Blood Type,Fruit Type,Bounty
2,Absalom,444.0,Thriller Bark Pirates (Mysterious Four) (former),Reporter Soldier Zombies and General Zombies C...,Deceased,December 30,1,0,0,0,West Blue,34.0,195.0,F,Paramecia,NaN
39,Kicking Claw Force,196.0,Arabasta Kingdom,Guards,Deceased,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
41,Aruyutayan V,292.0,Lvneel Kingdom,King,Deceased,NaN,0,0,0,0,North Blue,NaN,NaN,NaN,NaN,NaN
44,Ashura Doji,920.0,Mt. Atama Thieves,Bandit,Deceased,April 10,0,1,1,0,Grand Line,NaN,544.0,X,NaN,NaN
45,Asla,1153.0,Elbaph Royal Family,NaN,Deceased,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481,Vinsmoke Sora,841.0,Vinsmoke Family,Queen of the Germa Kingdom,Deceased,July 9,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1499,Warrior God,1175.0,NaN,NaN,Deceased,NaN,1,0,0,0,NaN,NaN,NaN,NaN,Mythical Zoan,NaN
1538,Zabo,241.0,NaN,NaN,Deceased,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1539,Zayde,391.0,Ohara Archaeologists,Archaeologist,Deceased,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1546,Zepo,850.0,Nox Pirates,Pirate,Deceased,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN